export type CertificateCategory = "web" | "mobile" | "ai" | "design" | "others"

export type FilterId = "all" | CertificateCategory

export const CERTIFICATE_FILTERS: { id: FilterId; label: string }[] = [
  { id: "all", label: "All" },
  { id: "web", label: "Web Dev" },
  { id: "mobile", label: "Mobile Dev" },
  { id: "ai", label: "AI & Data" },
  { id: "design", label: "UI/UX" },
  { id: "others", label: "Others" },
]

export interface CertificateItem {
  id: string
  title: string
  issuer: string
  issuedDate: string
  expirationDate?: string
  credentialId?: string
  credentialUrl?: string
  image: string
  description?: string
  skills?: string[]
  category: CertificateCategory
  /** Featured on the About page */
  featured?: boolean
}

const R2_URL = "https://cdn.fadhildev.my.id/certificate"

// Note: Replace the placeholder images with the actual JPG/PNG versions of your certificates
export const certificates: CertificateItem[] = [
  {
    id: "cert-conduct-ux-research ",
    title: "Conduct UX Research and Test Early Concepts",
    issuer: "Google",
    issuedDate: "Mar 2026",
    credentialId: "A7N2DNOYXFKL",
    image: `${R2_URL}/Conduct%20UX%20Research%20and%20Test%20Early%20Concepts.jpeg`,
    credentialUrl:
      "https://www.coursera.org/account/accomplishments/verify/A7N2DNOYXFKL",
    skills: ["UX Research", "User Testing"],
    category: "design",
  },
  {
    id: "cert-google-prompt",
    title: "Start Writing Prompts like a Pro",
    issuer: "Google",
    issuedDate: "Mar 2026",
    credentialId: "CR3KMGPMS69O",
    image: `${R2_URL}/Start%20Writing%20Prompts%20like%20a%20Pro.jpeg`,
    credentialUrl:
      "https://www.coursera.org/account/accomplishments/verify/CR3KMGPMS69O",
    skills: ["AI Prompting"],
    category: "ai",
  },
  {
    id: "cert-google-wireframing",
    title: "Build Wireframes and Low-Fidelity Prototypes",
    issuer: "Google",
    issuedDate: "Mar 2026",
    credentialId: "C8VRBMBHB479",
    image: `${R2_URL}/Build%20Wireframes%20and%20Low-Fidelity%20Prototypes.jpeg`,
    credentialUrl:
      "https://www.coursera.org/account/accomplishments/verify/C8VRBMBHB479",
    skills: ["Wireframing"],
    category: "design",
  },
  {
    id: "cert-unisa-ustep",
    title: "U-STEP (UNISA Standardized Test of English Proficiency)",
    issuer: "Universitas 'Aisyiyah (UNISA) Yogyakarta",
    issuedDate: "Aug 2025",
    credentialId: "1537/U-STEP/PPB/VIII/2025",
    image: `${R2_URL}/Sertifikat_U-STEP_UNISA.jpg`,
    credentialUrl:
      "https://drive.google.com/file/d/1aqnxjqPcWJfDT2i7MnUm7smWM71Q3Dz4/view?usp=sharing",
    skills: ["English"],
    category: "others",
  },
  {
    id: "cert-dicoding-python",
    title: "Memulai Pemrograman dengan Python",
    issuer: "Dicoding Indonesia",
    issuedDate: "Jan 2026",
    expirationDate: "Jan 2029",
    credentialId: "L4PQ2N6G2ZO1",
    image: `${R2_URL}/Memulai%20Pemrograman%20dengan%20Python.jpg`,
    credentialUrl: "https://www.dicoding.com/certificates/L4PQ2N6G2ZO1",
    skills: ["Python"],
    category: "others",
  },
  {
    id: "cert-dicoding-prompt-eng",
    title: "Prompt Engineering untuk Software Developer",
    issuer: "Dicoding Indonesia",
    issuedDate: "Jan 2026",
    expirationDate: "Jan 2029",
    credentialId: "98XWOMLJ9ZM3",
    image: `${R2_URL}/Prompt%20Engineering%20untuk%20Software%20Developer.jpg`,
    credentialUrl: "https://www.dicoding.com/certificates/98XWOMLJ9ZM3",
    skills: ["AI Prompting", "Generative AI"],
    category: "ai",
  },
  {
    id: "cert-google-ux-empathize",
    title: "Start the UX Design Process: Empathize, Define, and Ideate",
    issuer: "Google",
    issuedDate: "Dec 2025",
    credentialId: "NF7POVGVZ2VG",
    image: `${R2_URL}/Start%20the%20UX%20Design%20Process.jpeg`,
    credentialUrl:
      "https://www.coursera.org/account/accomplishments/verify/NF7POVGVZ2VG",
    skills: ["User Experience (UX)", "UX Research"],
    category: "design",
  },
  {
    id: "cert-dicoding-flutter-intermediate",
    title: "Belajar Pengembangan Aplikasi Flutter Intermediate",
    issuer: "Dicoding Indonesia",
    issuedDate: "Dec 2025",
    expirationDate: "Dec 2028",
    credentialId: "QLZ96E647Z5D",
    image: `${R2_URL}/Belajar%20Pengembangan%20Aplikasi%20Flutter%20Intermediate.jpg`,
    credentialUrl: "https://www.dicoding.com/certificates/QLZ96E647Z5D",
    skills: ["Flutter", "Dart"],
    category: "mobile",
  },
  {
    id: "cert-google-ux-foundation",
    title: "Foundations of User Experience (UX) Design",
    issuer: "Google",
    issuedDate: "Dec 2025",
    credentialId: "SIY6OGYDHQ7R",
    image: `${R2_URL}/Foundations%20of%20User%20Experience%20(UX)%20Design.jpg`,
    featured: true,
    credentialUrl:
      "https://www.coursera.org/account/accomplishments/verify/SIY6OGYDHQ7R",
    skills: ["User Experience (UX)"],
    category: "design",
  },
  {
    id: "cert-dicoding-multiplatform",
    title: "Multi-Platform App Developer (Flutter)",
    issuer: "Dicoding Indonesia",
    issuedDate: "Nov 2025",
    credentialId: "BC25/GRAD/XXV-11/BC25B053",
    featured: true,
    image: `${R2_URL}/Multi%20Platform%20App%20Developer%20(Flutter).jpg`,
    credentialUrl:
      "https://drive.google.com/file/d/1Ew1q2eswyBto2V5-biSx0wb6HOG8tjhh/view?usp=sharing",
    skills: [
      "Flutter",
      "Dart",
      "Mobile Application Development",
      "Project Management",
    ],
    category: "mobile",
  },
  {
    id: "cert-bnsp-helpdesk",
    title: "Helpdesk Technician - BNSP",
    issuer: "Badan Nasional Sertifikasi Profesi (BNSP)",
    issuedDate: "Sep 2025",
    expirationDate: "Sep 2028",
    credentialId: "62024 3512500000072025",
    image: `${R2_URL}/Sertif_Helpdesk_BNSP.jpg`,
    featured: true,
    skills: ["Help Desk Support", "Technical Support"],
    category: "others",
  },
  {
    id: "cert-dicoding-meniti-karier",
    title: "Meniti Karier sebagai Software Developer",
    issuer: "Dicoding Indonesia",
    issuedDate: "Sep 2025",
    expirationDate: "Sep 2028",
    credentialId: "NVP7JOVMOXR0",
    image: `${R2_URL}/Meniti%20Karier%20sebagai%20Software%20Developer.jpg`,
    credentialUrl: "https://www.dicoding.com/certificates/NVP7JOVMOXR0",
    category: "others",
  },
  {
    id: "cert-dicoding-ml-flutter",
    title: "Belajar Penerapan Machine Learning untuk Flutter",
    issuer: "Dicoding Indonesia",
    issuedDate: "Sep 2025",
    expirationDate: "Sep 2028",
    credentialId: "JLX15DY85Z72",
    image: `${R2_URL}/Belajar%20Penerapan%20ML%20Pada%20Flutter.jpg`,
    credentialUrl: "https://www.dicoding.com/certificates/JLX15DY85Z72",
    skills: ["Firebase", "Artificial Intelligence (AI)", "Flutter"],
    category: "ai",
  },
  {
    id: "cert-dicoding-dasar-ai",
    title: "Belajar Dasar AI",
    issuer: "Dicoding Indonesia",
    issuedDate: "Sep 2025",
    expirationDate: "Sep 2028",
    credentialId: "QLZ96QKJMZ5D",
    image: `${R2_URL}/Belajar_Dasar_AI.jpg`,
    skills: ["Artificial Intelligence (AI)"],
    credentialUrl: "https://www.dicoding.com/certificates/QLZ96QKJMZ5D",
    category: "ai",
  },
  {
    id: "cert-dicoding-solid",
    title: "Belajar Prinsip Pemrograman SOLID",
    issuer: "Dicoding Indonesia",
    issuedDate: "Sep 2025",
    expirationDate: "Sep 2028",
    credentialId: "L4PQ2G48OZO1",
    image: `${R2_URL}/Belajar%20Prinsip%20Pemrograman%20SOLID.jpg`,
    credentialUrl: "https://www.dicoding.com/certificates/L4PQ2G48OZO1",
    skills: ["SOLID"],
    category: "others",
  },
  {
    id: "cert-dicoding-flutter-fundamental",
    title: "Belajar Fundamental Aplikasi Flutter",
    issuer: "Dicoding Indonesia",
    issuedDate: "Sep 2025",
    expirationDate: "Sep 2028",
    credentialId: "72ZDK9W1VPYW",
    image: `${R2_URL}/Belajar%20Fundamental%20Aplikasi%20Flutter.jpg`,
    credentialUrl: "https://www.dicoding.com/certificates/72ZDK9W1VPYW",
    skills: ["Flutter", "Dart"],
    category: "mobile",
  },
  {
    id: "cert-dicoding-flutter-pemula",
    title: "Belajar Membuat Aplikasi Flutter untuk Pemula",
    issuer: "Dicoding Indonesia",
    issuedDate: "Aug 2025",
    expirationDate: "Aug 2028",
    credentialId: "1RXYQY16KZVM",
    image: `${R2_URL}/Belajar%20Membuat%20Aplikasi%20Flutter%20untuk%20Pemula.jpg`,
    credentialUrl: "https://www.dicoding.com/certificates/1RXYQY16KZVM",
    skills: ["Flutter", "Dart"],
    category: "mobile",
  },
  {
    id: "cert-telkom-llm",
    title: "The Fundamentals of Large Language Model",
    issuer: "Digistar Club by Telkom Indonesia",
    issuedDate: "Feb 2025",
    credentialId: "347/SC-DA/DigiClub/I/2025",
    image: `${R2_URL}/The%20Fundamentals%20of%20Large%20Language%20Model.jpg`,
    skills: ["Artificial Intelligence (AI)", "Large Language Models (LLM)"],
    category: "ai",
  },
  {
    id: "cert-dicoding-dart",
    title: "Memulai Pemrograman dengan Dart",
    issuer: "Dicoding Indonesia",
    issuedDate: "Jul 2025",
    expirationDate: "Jul 2028",
    credentialId: "0LZ05D5YNX65",
    image: `${R2_URL}/Memulai%20Pemrograman%20dengan%20Dart.jpg`,
    credentialUrl: "https://www.dicoding.com/certificates/0LZ05D5YNX65",
    skills: ["Dart"],
    category: "mobile",
  },
  {
    id: "cert-dicoding-git",
    title: "Belajar Dasar Git dengan GitHub",
    issuer: "Dicoding Indonesia",
    issuedDate: "Jul 2025",
    expirationDate: "Jul 2028",
    credentialId: "RVZKG4KOOXD5",
    image: `${R2_URL}/Sertifikat_Belajar%20Dasar%20Git%20dengan%20GitHub_Dicoding.jpg`,
    credentialUrl: "https://www.dicoding.com/certificates/RVZKG4KOOXD5",
    skills: ["GitHub", "Git", "Gitlab"],
    category: "others",
  },
  {
    id: "cert-dicoding-logic",
    title: "Pengenalan ke Logika Pemrograman (Programming Logic 101)",
    issuer: "Dicoding Indonesia",
    issuedDate: "Jul 2025",
    expirationDate: "Jul 2028",
    credentialId: "L4PQ2M4D2ZO1",
    image: `${R2_URL}/Pengenalan%20ke%20Logika%20Pemrograman%20(Programming%20Logic%20101).jpg`,
    credentialUrl: "https://www.dicoding.com/certificates/L4PQ2M4D2ZO1",
    skills: ["Programming Logic"],
    category: "others",
  },
  {
    id: "cert-ibm-granite",
    title: "Code Generation and Optimization Using IBM Granite",
    issuer: "IBM",
    issuedDate: "Jul 2025",
    image: `${R2_URL}/Code%20Generation%20and%20Optimization%20Using%20IBM%20Granite.png`,
    credentialUrl:
      "https://www.credly.com/badges/96fdd3eb-0df9-49c0-9f9c-9117399754e9/linked_in_profile",
    skills: ["Code Generation", "Generative AI", "AI Prompting", "LLM"],
    category: "ai",
  },
  {
    id: "cert-dicoding-pemrograman-dasar",
    title: "Memulai Dasar Pemrograman untuk Menjadi Pengembang Software",
    issuer: "Dicoding Indonesia",
    issuedDate: "Jul 2025",
    expirationDate: "Jul 2028",
    credentialId: "1OP8JYG5LPQK",
    image: `${R2_URL}/Memulai%20Dasar%20Pemrograman%20untuk%20Menjadi%20Pengembang%20Software.jpg`,
    credentialUrl: "https://www.dicoding.com/certificates/1OP8JYG5LPQK",
    category: "others",
  },
  {
    id: "cert-telkom-msib6",
    title: "MSIB 6 Kampus Merdeka - PT Telkom Indonesia",
    issuer: "Telkom Indonesia",
    issuedDate: "Jul 2024",
    image: `${R2_URL}/Sertifikat_Magang_MSIB_Telkom%20Indonesia.jpg`,
    credentialUrl:
      "https://drive.google.com/file/d/1wXttR1V9d6DWFucCl_L1LhX_NRO4g50G/view?usp=sharing",
    skills: [
      "Public Speaking",
      "Agile",
      "Project Management",
      "Problem Solving",
    ],
    category: "others",
  },
  {
    id: "cert-greatlearning-datamining",
    title: "Data Mining",
    issuer: "Great Learning",
    issuedDate: "Jan 2025",
    image: `${R2_URL}/DataMining_GreatLearning.jpg`,
    credentialUrl: "https://www.mygreatlearning.com/certificate/VCVIVMYF",
    skills: ["Data Analysis", "Jupyter", "Data Manipulation", "Data Mining"],
    category: "ai",
  },
  {
    id: "cert-dicoding-devops",
    title: "Belajar Dasar-Dasar DevOps",
    issuer: "Dicoding Indonesia",
    issuedDate: "Oct 2024",
    expirationDate: "Oct 2027",
    credentialId: "L4PQ51LNQZO1",
    image: `${R2_URL}/Belajar_Dasar_DevOps.jpg`,
    credentialUrl: "https://www.dicoding.com/certificates/L4PQ51LNQZO1",
    skills: ["DevOps", "CALMS Framework"],
    category: "others",
  },
  {
    id: "cert-pijarmahir-scrum",
    title: "Mahir SCRUM untuk Pengembangan Produk Digital",
    issuer: "Pijar Mahir",
    issuedDate: "Feb 2024",
    credentialId: "2024/02/2985/980699",
    image: `${R2_URL}/Mahir%20SCRUM%20untuk%20Pengembangan%20Produk%20Digital.jpg`,
    credentialUrl: "https://pijarmahir.id/sertifikat/xAl9GGFx9E",
    skills: ["Agile Project Management", "Scrum"],
    category: "others",
  },
  {
    id: "cert-alterra-frontend",
    title: "2023 Complete Front-End Engineer Career with ReactJS",
    issuer: "Alterra Academy",
    issuedDate: "Jan 2024",
    credentialId: "243/SER/B2G-MKP/I/2024",
    image: `${R2_URL}/Complete%20Front-End%20Engineer%20Career%20with%20ReactJS.jpg`, // User provided pdf earlier, expected to convert to PNG
    featured: true,
    credentialUrl: `https://drive.google.com/file/d/1h7IxDECLekH2zE5ARQQaZdVXmYMHsSac/view`,
    skills: [
      "React",
      "HTML",
      "CSS",
      "JavaScript",
      "Tailwind CSS",
      "Redux",
      "Figma",
      "REST APIs",
    ],
    category: "web",
  },
  {
    id: "cert-dicoding-auth",
    title: "Autentikasi dan Otorisasi Pada RestAPI",
    issuer: "Dicoding Indonesia",
    issuedDate: "Jan 2024",
    image: `${R2_URL}/Autentikasi%20dan%20Otorisasi%20Pada%20RestAPI.jpg`,
    skills: ["REST APIs", "Authentication Systems"],
    category: "web",
  },
  {
    id: "cert-codingstudio-fe2",
    title: "Fundamental Front-End Web Development II",
    issuer: "Coding Studio",
    issuedDate: "Dec 2023",
    credentialId: "19731",
    credentialUrl: `${R2_URL}/CodingStudio_Fundamental-Front-End-Web-Development%20(2).jpg`,
    image: `${R2_URL}/CodingStudio_Fundamental-Front-End-Web-Development%20(2).jpg`,
    category: "web",
  },
  {
    id: "cert-codingstudio-fe1",
    title: "Fundamental Front-End Web Development I",
    issuer: "Coding Studio",
    issuedDate: "Dec 2023",
    credentialId: "19731",
    image: `${R2_URL}/CodingStudio_Fundamental-Front-End-Web-Development%20(1).jpg`,
    category: "web",
  },
]
