export type CertificateCategory = "web" | "mobile" | "ai" | "design" | "others"

export type FilterId = "all" | CertificateCategory

export const CERTIFICATE_FILTERS: { id: FilterId; label: string }[] = [
  { id: "all", label: "All" },
  { id: "web", label: "Web Dev" },
  { id: "mobile", label: "Mobile Dev" },
  { id: "ai", label: "AI & Data" },
  { id: "design", label: "UI/UX" },
  { id: "others", label: "Others" },
]

export interface CertificateItem {
  id: string
  title: string
  issuer: string
  issuedDate: string
  expirationDate?: string
  credentialId?: string
  credentialUrl?: string
  image: string
  description?: string
  skills?: string[]
  category: CertificateCategory
}

const R2_URL = "https://cdn.fadhildev.my.id/certificate"

// Note: Replace the placeholder images with the actual JPG/PNG versions of your certificates
export const certificates: CertificateItem[] = [
  {
    id: "cert-google-prompt",
    title: "Start Writing Prompts like a Pro",
    issuer: "Google",
    issuedDate: "Mar 2026",
    credentialId: "CR3KMGPMS69O",
    image: `${R2_URL}/Start_Writing_Prompts_like_a_Pro.png`, // Placeholder
    skills: ["AI Prompting"],
    category: "ai",
  },
  {
    id: "cert-google-wireframing",
    title: "Build Wireframes and Low-Fidelity Prototypes",
    issuer: "Google",
    issuedDate: "Mar 2026",
    credentialId: "C8VRBMBHB479",
    image: `${R2_URL}/Build_Wireframes_and_Low-Fidelity_Prototypes.png`,
    skills: ["Wireframing"],
    category: "design",
  },
  {
    id: "cert-unisa-ustep",
    title: "U-STEP (UNISA Standardized Test of English Proficiency)",
    issuer: "Universitas 'Aisyiyah (UNISA) Yogyakarta",
    issuedDate: "Aug 2025",
    credentialId: "1537/U-STEP/PPB/VIII/2025",
    image: `${R2_URL}/Sertifikat_U-STEP_UNISA_Fadhil_Alif_Priyatno.png`,
    skills: ["English"],
    category: "others",
  },
  {
    id: "cert-dicoding-python",
    title: "Memulai Pemrograman dengan Python",
    issuer: "Dicoding Indonesia",
    issuedDate: "Jan 2026",
    expirationDate: "Jan 2029",
    credentialId: "L4PQ2N6G2ZO1",
    image: `${R2_URL}/Memulai_Pemrograman_dengan_Python.png`,
    skills: ["Python"],
    category: "others",
  },
  {
    id: "cert-dicoding-prompt-eng",
    title: "Prompt Engineering untuk Software Developer",
    issuer: "Dicoding Indonesia",
    issuedDate: "Jan 2026",
    expirationDate: "Jan 2029",
    credentialId: "98XWOMLJ9ZM3",
    image: `${R2_URL}/Prompt_Engineering_untuk_Software_Developer.png`,
    skills: ["AI Prompting", "Generative AI"],
    category: "ai",
  },
  {
    id: "cert-google-ux-empathize",
    title: "Start the UX Design Process: Empathize, Define, and Ideate",
    issuer: "Google",
    issuedDate: "Dec 2025",
    credentialId: "NF7POVGVZ2VG",
    image: `${R2_URL}/Coursera_NF7POVGVZ2VG.png`,
    skills: ["User Experience (UX)", "UX Research"],
    category: "design",
  },
  {
    id: "cert-dicoding-flutter-intermediate",
    title: "Belajar Pengembangan Aplikasi Flutter Intermediate",
    issuer: "Dicoding Indonesia",
    issuedDate: "Dec 2025",
    expirationDate: "Dec 2028",
    credentialId: "QLZ96E647Z5D",
    image: `${R2_URL}/sertifikat_course_flutter_intermediate.png`,
    skills: ["Flutter", "Dart"],
    category: "mobile",
  },
  {
    id: "cert-google-ux-foundation",
    title: "Foundations of User Experience (UX) Design",
    issuer: "Google",
    issuedDate: "Dec 2025",
    credentialId: "SIY6OGYDHQ7R",
    image: `${R2_URL}/Coursera_SIY6OGYDHQ7R_Fadhil_Alif_P.png`,
    skills: ["User Experience (UX)"],
    category: "design",
  },
  {
    id: "cert-dicoding-multiplatform",
    title: "Multi-Platform App Developer (Flutter)",
    issuer: "Dicoding Indonesia",
    issuedDate: "Nov 2025",
    credentialId: "BC25/GRAD/XXV-11/BC25B053",
    image: `${R2_URL}/BEKUP_Create_Sertifikat.png`,
    skills: [
      "Flutter",
      "Dart",
      "Mobile Application Development",
      "Project Management",
    ],
    category: "mobile",
  },
  {
    id: "cert-bnsp-helpdesk",
    title: "Helpdesk Technician - BNSP",
    issuer: "Badan Nasional Sertifikasi Profesi (BNSP)",
    issuedDate: "Sep 2025",
    expirationDate: "Sep 2028",
    credentialId: "62024 3512500000072025",
    image: `${R2_URL}/Sertif_BNSP_Helpdesk_Technician.png`,
    skills: ["Help Desk Support", "Technical Support"],
    category: "others",
  },
  {
    id: "cert-dicoding-meniti-karier",
    title: "Meniti Karier sebagai Software Developer",
    issuer: "Dicoding Indonesia",
    issuedDate: "Sep 2025",
    expirationDate: "Sep 2028",
    credentialId: "NVP7JOVMOXR0",
    image: `${R2_URL}/Meniti_Karier_sebagai_Software_Developer.png`,
    category: "others",
  },
  {
    id: "cert-dicoding-ml-flutter",
    title: "Belajar Penerapan Machine Learning untuk Flutter",
    issuer: "Dicoding Indonesia",
    issuedDate: "Sep 2025",
    expirationDate: "Sep 2028",
    credentialId: "JLX15DY85Z72",
    image: `${R2_URL}/Belajar_Penerapan_Machine_Learning_untuk_Flutter.png`,
    skills: ["Firebase", "Artificial Intelligence (AI)", "Flutter"],
    category: "ai",
  },
  {
    id: "cert-dicoding-dasar-ai",
    title: "Belajar Dasar AI",
    issuer: "Dicoding Indonesia",
    issuedDate: "Sep 2025",
    expirationDate: "Sep 2028",
    credentialId: "QLZ96QKJMZ5D",
    image: `${R2_URL}/Belajar_Dasar_AI.png`,
    skills: ["Artificial Intelligence (AI)"],
    category: "ai",
  },
  {
    id: "cert-dicoding-solid",
    title: "Belajar Prinsip Pemrograman SOLID",
    issuer: "Dicoding Indonesia",
    issuedDate: "Sep 2025",
    expirationDate: "Sep 2028",
    credentialId: "L4PQ2G48OZO1",
    image: `${R2_URL}/Belajar_Prinsip_Pemrograman_SOLID.png`,
    skills: ["SOLID"],
    category: "others",
  },
  {
    id: "cert-dicoding-flutter-fundamental",
    title: "Belajar Fundamental Aplikasi Flutter",
    issuer: "Dicoding Indonesia",
    issuedDate: "Sep 2025",
    expirationDate: "Sep 2028",
    credentialId: "72ZDK9W1VPYW",
    image: `${R2_URL}/Belajar_Fundamental_Aplikasi_Flutter.png`,
    skills: ["Flutter", "Dart"],
    category: "mobile",
  },
  {
    id: "cert-dicoding-flutter-pemula",
    title: "Belajar Membuat Aplikasi Flutter untuk Pemula",
    issuer: "Dicoding Indonesia",
    issuedDate: "Aug 2025",
    expirationDate: "Aug 2028",
    credentialId: "1RXYQY16KZVM",
    image: `${R2_URL}/Belajar_Membuat_Aplikasi_Flutter_Untuk_Pemula.png`,
    skills: ["Flutter", "Dart"],
    category: "mobile",
  },
  {
    id: "cert-telkom-llm",
    title: "The Fundamentals of Large Language Model",
    issuer: "Digistar Club by Telkom Indonesia",
    issuedDate: "Feb 2025",
    credentialId: "347/SC-DA/DigiClub/I/2025",
    image: `${R2_URL}/Fundamentals_of_LLM_Telkom.png`,
    skills: ["Artificial Intelligence (AI)", "Large Language Models (LLM)"],
    category: "ai",
  },
  {
    id: "cert-dicoding-dart",
    title: "Memulai Pemrograman dengan Dart",
    issuer: "Dicoding Indonesia",
    issuedDate: "Jul 2025",
    expirationDate: "Jul 2028",
    credentialId: "0LZ05D5YNX65",
    image: `${R2_URL}/Memulai_Pemrograman_dengan_Dart.png`,
    skills: ["Dart"],
    category: "mobile",
  },
  {
    id: "cert-dicoding-git",
    title: "Belajar Dasar Git dengan GitHub",
    issuer: "Dicoding Indonesia",
    issuedDate: "Jul 2025",
    expirationDate: "Jul 2028",
    credentialId: "RVZKG4KOOXD5",
    image: `${R2_URL}/Sertifikat_Belajar_Dasar_Git.png`,
    skills: ["GitHub", "Git", "Gitlab"],
    category: "others",
  },
  {
    id: "cert-dicoding-logic",
    title: "Pengenalan ke Logika Pemrograman (Programming Logic 101)",
    issuer: "Dicoding Indonesia",
    issuedDate: "Jul 2025",
    expirationDate: "Jul 2028",
    credentialId: "L4PQ2M4D2ZO1",
    image: `${R2_URL}/Sertifikat_Pengenalan_Logika_Pemrograman.png`,
    category: "others",
  },
  {
    id: "cert-ibm-granite",
    title: "Code Generation and Optimization Using IBM Granite",
    issuer: "IBM",
    issuedDate: "Jul 2025",
    image: `${R2_URL}/Certificate_Code_Generation_IBM_Granite.png`,
    skills: ["Code Generation", "Generative AI", "AI Prompting", "LLM"],
    category: "ai",
  },
  {
    id: "cert-dicoding-pemrograman-dasar",
    title: "Memulai Dasar Pemrograman untuk Menjadi Pengembang Software",
    issuer: "Dicoding Indonesia",
    issuedDate: "Jul 2025",
    expirationDate: "Jul 2028",
    credentialId: "1OP8JYG5LPQK",
    image: `${R2_URL}/Memulai_Dasar_Pemrograman.png`,
    category: "others",
  },
  {
    id: "cert-telkom-msib6",
    title: "MSIB 6 Kampus Merdeka - PT Telkom Indonesia",
    issuer: "Telkom Indonesia",
    issuedDate: "Jul 2024",
    image: `${R2_URL}/SERTIF_TELKOM_INDONESIA_MSIB6.png`,
    skills: [
      "Public Speaking",
      "Agile",
      "Project Management",
      "Problem Solving",
    ],
    category: "others",
  },
  {
    id: "cert-greatlearning-datamining",
    title: "Data Mining",
    issuer: "Great Learning",
    issuedDate: "Jan 2025",
    image: `${R2_URL}/Fadhil_Alif_Data_Mining_Course.png`,
    skills: ["Data Analysis", "Jupyter", "Data Manipulation", "Data Mining"],
    category: "ai",
  },
  {
    id: "cert-dicoding-devops",
    title: "Belajar Dasar-Dasar DevOps",
    issuer: "Dicoding Indonesia",
    issuedDate: "Oct 2024",
    expirationDate: "Oct 2027",
    credentialId: "L4PQ51LNQZO1",
    image: `${R2_URL}/SERTIFIKAT_IDCAMP_DEVOPS.png`,
    skills: ["DevOps", "CALMS Framework"],
    category: "others",
  },
  {
    id: "cert-pijarmahir-scrum",
    title: "Mahir SCRUM untuk Pengembangan Produk Digital",
    issuer: "Pijar Mahir",
    issuedDate: "Feb 2024",
    credentialId: "2024/02/2985/980699",
    image: `${R2_URL}/Pijar_Mahir_Mahir_SCRUM.png`,
    skills: ["Agile Project Management", "Scrum"],
    category: "others",
  },
  {
    id: "cert-alterra-frontend",
    title: "2023 Complete Front-End Engineer Career with ReactJS",
    issuer: "Alterra Academy",
    issuedDate: "Jan 2024",
    credentialId: "243/SER/B2G-MKP/I/2024",
    image: `${R2_URL}/Sertifikat_243_SER_B2G-MKP_I_2024_PNG.png`, // User provided pdf earlier, expected to convert to PNG
    credentialUrl: `${R2_URL}/Sertifikat%20243_SER_B2G-MKP_I_2024%20-%20Fadhil%20Alif%20Priyatno.pdf`,
    skills: [
      "React",
      "HTML",
      "CSS",
      "JavaScript",
      "Tailwind CSS",
      "Redux",
      "Figma",
      "REST APIs",
    ],
    category: "web",
  },
  {
    id: "cert-dicoding-auth",
    title: "Autentikasi dan Otorisasi Pada RestAPI",
    issuer: "Dicoding Indonesia",
    issuedDate: "Jan 2024",
    image: `${R2_URL}/devcoach-122-back-end.png`,
    skills: ["REST APIs", "Authentication Systems"],
    category: "web",
  },
  {
    id: "cert-codingstudio-fe2",
    title: "Fundamental Front-End Web Development II",
    issuer: "Coding Studio",
    issuedDate: "Dec 2023",
    credentialId: "19731",
    credentialUrl: `${R2_URL}/CodingStudio_Fundamental-Front-End-Web-Development%20(2).jpg`,
    image: `${R2_URL}/CodingStudio_Fundamental-Front-End-Web-Development%20(2).jpg`,
    category: "web",
  },
  {
    id: "cert-codingstudio-fe1",
    title: "Fundamental Front-End Web Development I",
    issuer: "Coding Studio",
    issuedDate: "Dec 2023",
    credentialId: "19731",
    image: `${R2_URL}/Certificate_Fundamental-Front-End-Web-Development-I.png`,
    category: "web",
  },
]
